<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJWZcJpc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJWZcJpc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJWZcJpc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJWZcJpc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJWZcJpc\App_KernelDevDebugContainer([
    'container.build_hash' => 'JWZcJpc',
    'container.build_id' => '105d37f9',
    'container.build_time' => 1618226043,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJWZcJpc');
